# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "GDG DevFest Galicia 2017"
email: "info@gdggalicia.com"
description: "GDG DevFest es un conjunto de eventos celebrados en todo el mundo"
baseurl: ""
url: "http://devfest.gdggalicia.com"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-109987827-1"
googleAnalyticsSiteUrl: "devfest.gdggalicia.com"
siteVerification: "EXdO3QQvjtS2RGFWXqXD6rzYECtFDpWrRRI0Cc31xbc"

# Organizer Info
organizerName: "GDG Galicia"
organizerAlternateName: "GDG"
organizerDescription: "Comunidad abierta de voluntarios geeks que crean proyectos y comparten experiencias sobre tecnologías de Google con pasión."
organizerEmail: "info@gdgvigo.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://developers.google.com/groups/chapter/106284181570326060854/"

# Head
metaKeywords: "event, galicia, gdg, devfest, google, programming, developers, "
twitterAccount: "@GDGVigo"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://gdgvigo.typeform.com/to/JvDH2h"
c4sponsorsUrl: "https://gdgvigo.typeform.com/to/Tx9PPS"


# Navigation
navigationLinks:
 - {permalink: "/", text: "DevFest"}
 - {permalink: "/code-of-conduct/", text: "Código de Conducta"}
 - {permalink: "/logistics/", text: "Ubicación"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/schedule/", text: "Agenda"}
 - {permalink: "/team/", text: "Equipo"}
 - {permalink: "/blog/", text: "Blog"}
bottomNavigationLinks:
 - {link: "https://gdgvigo.typeform.com/to/JvDH2h", text: "Conviértete en speaker"}
rightNavigationButtons:
 - {link: "https://gdgvigo.typeform.com/to/JvDH2h", text: "Conviértete en speaker"}

# Hero Block
heroImage: "fireworks.jpg"
heroTitle: "GDG DevFest <typeout> 2017"
eventDate: "16 Diciembre 2017"
typeoutTextValues: '"", "Ourense", "Santiago", "Vigo", "Galicia"'
typeoutFallback: ""
heroButtons:
 - {link: "https://gdgvigo.typeform.com/to/JvDH2h", text: "Conviértete en speaker"}
 - {link: "#tickets", text: "Patrocínanos!"}
 - {link: "https://www.meetup.com/es-ES/GDGVigo/events/242440940/", text: "Entrada gratuita"}

# About Block
aboutTitle: "Sobre el GDG DevFest"
aboutBlock:
 - {title: "Conferencias", image: "gdg-devfest.png", text: "En el GDG DevFests Galicia 2017 se realizarán 6 conferencias por unos pedazo de speakers que nos hablarán de las últimas tecnologías con las que está trabando." }
 - {title: "Workshops", image: "gdgDevelopers.png", text: "Un dia entero de workshops que serán sesiones más participativas en las que se harán demos en tiempo real de productos y en las que puedes acercarte con tu propio portátil y resolver cualquier duda que te surja." }

# Statistic Block
statisticBlockImage: "numbers-front.jpg"
statisticBlock:
 - {count: "300", specialCharacter: "+", info: "asistentes"}
 - {count: "6", specialCharacter: "+", info: "horas"}
 - {count: "11", specialCharacter: "+", info: "speakers"}
 - {count: "2", specialCharacter: "", info: "tracks"}


# Latest News Block
latestNewsTitle: "Últimas noticias"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "Más Speakers"

# Location Block
locationBlockTitle: "Ubicación"
eventLocationName: "Facultade de Ciencias Sociais e da Comunicación"
eventLocationLink: "http://csc.uvigo.es/"
eventStreetAddress: "Campus Universitario da Xunqueira, S/N"
eventAddressLocality: "Pontevedra"
eventAddressLocalityRegion: "Pontevedra"
eventPostalCode: "36005"
eventAddressCountry: "Spain"
eventStartTime: "2014-10-25T09:00"
eventDoorTime: "09:00"
eventEndTime: "2014-10-25T20:00"
eventPlaceCoordinates: "42.440142, -8.638062"
mapCenterCoordinates: "42.440142, -8.638062"
mapMobileCenterCoordinates: "42.440142, -8.638062"

# Venue Block
venueBlockTitle: "Instalaciones"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueTitle: "Facultade de Ciencias Sociais e da Comunicación"
venueFeatures: ["salón de actos principal con cabida para más de 300 personas", "Aulas para workshops"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfestgal"
twitterFeed: ""

# Partners Block
organizersTitle: "Organizadores"
partnersTitle: "Patrocinadores"
partnersC4sponsorsButton: "Hazte sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscríbete para recibir novedades"
subscribeAction: "//gdgvigo.us16.list-manage.com/subscribe/post?u=66b4bb03b0b8f95169952466e&amp;id=50c4e234dc"

# Tickets Block
ticketsTitle: "Patrocinios"
ticketsOffers:
 -
  name: "Shy guy"
  price: "150"
  priceCurrency: "€"
  ticketsNumber: "150"
  buyButtonLink: "https://gdgvigo.typeform.com/to/Tx9PPS"
  buyButtonText: "Patrocina ahora"
  ticketContentList: ["Logo en web", "Diapositiva conjunta", "Mención en social media"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Big boss"
  price: "800"
  priceCurrency: "€"
  ticketsNumber: "800"
  featured: true
  buyButtonLink: "https://gdgvigo.typeform.com/to/Tx9PPS"
  buyButtonText: "Patrocina ahora"
  ticketContentList: ["Todo lo incluído en High five ", "Logo en los títulos de la grabación", "Stand para contratar gente"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
 -
  name: "High five"
  price: "400"
  priceCurrency: "€"
  ticketsNumber: "400"
  buyButtonLink: "https://gdgvigo.typeform.com/to/Tx9PPS"
  buyButtonText: "Patrocina ahora"
#  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Todo lo incluído en Shy guy", "Diapositiva propia", "Logo en Camisetas"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"


# Footer
socialLinks:
 - {link: "https://plus.google.com/communities/104458805154699272096", icon: "google-plus"}
 - {link: "https://twitter.com/gdgvigo", icon: "twitter"}
 - {link: "https://www.facebook.com/pg/googledevelopergroupvigo/about/", icon: "facebook"}
 - {link: "https://github.com/GDGVigo", icon: "github"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:info@gdggalicia.com", text: "info@gdggalicia.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/code-of-conduct/", text: "Código de conducta"}

# Blog
blogTitle: "Últimas noticias"
blogCommentsEnabled: false
discusShortName: "devfest"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Sobre nosotros"
aboutUs: "Somos un equipo de 8 organizadores de GDG, cada uno con su propia area de especialización. Nos apasiona lo que hacemos para la comunidad: ayudar a gente, conocer personas y organizar eventos. Estamos deseando conocerte, por lo que si te cruzas con alguno de nosotros en el evento y te apetece hablar, páranos y dinos Hola!"

# Logistics Find Way Block
findWayTitle: "Cómo llegar?"
findWayDistance: "Distancia"
findWayDriving: "EN COCHE"
findWayWalking: "CAMINANDO"
findWayBicycling: "EN BICI"
findWayTransit: "TRANSPORTE"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "42.240065, -8.720963"
logisticsMapMobileCenterCoordinates: "42.240065, -8.720963"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "main-venue.jpg"
directionDetailsTitle: "Facultade de Ciencias Sociais<br/> e da Comunicación"
#directionDetailsCards:
# - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
# - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
# - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
#directionDetailsWideCards:
# -
#  title: "Questions?"
#  subCards:
#   -
#    title: "Hotels"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#   -
#    title: "Registration"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#   -
#    title: "Attendance Details"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Vigo"
hackathonAddressLocalityRegion: "Vigo"
hackathonPostalCode: ""
hackathonAddressCountry: "Spain"
hackathonTimeTitle: "Firebase Appfest"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "42.240065, -8.720963"
hackathonMapCenterCoordinates: "42.240065, -8.720963"
hackathonMapMobileCenterCoordinates: "42.240065, -8.720963"
